### ISSUE TITLE
OAuthTokenGenerator doesn't provide clear instructions on how to authorize with a Web client

### ISSUE THREAD

**Issue by nilamo** [googleads/googleads-dotnet-lib#197]
Currently, it uses the default Google.Apis.Auth.OAuth2.LocalServerCodeReceiver, which always uses a random open port.  I'm not sure how OAuthTokenGenerator works that way, since you need to know the port ahead of time to authorize the redirect url in the Google Console.

As a quick fix, I made a custom implementation of ICodeReceiver that allowed me to set a port, but I don't think that's a real solution, just a hacky way to get what I needed quickly.  I'd suggest either adding a command line flag to specify a port if needed, or write to the console what port will be used before querying the remote server, so the user had a chance to add that specific redirect url to the Google Console, so there was a higher chance of success.

**Comment by AnashOommen** [comment]
You need to use either a Google credentials of type "Other". I filed https://github.com/googleapis/google-api-dotnet-client/issues/1316 to see if I can get a fix, will talk to the folks from the Cloud team to see what's the best way to handle this issue.

**Comment by AnashOommen** [comment]
I updated the [wiki](https://github.com/googleads/googleads-dotnet-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow)#step-1---creating-oauth2-credentials) with a fix.

**Comment by AnashOommen** [comment]
This should also be clarified in OAuthTokenGenerator application.

**Comment by AnashOommen** [comment]
Fixed in v24.3.0.

**Comment by kschweikert27** [comment]
I'm using v24.5 and the issue is still not fixed.  
As stated earlier, it uses the default Google.Apis.Auth.OAuth2.LocalServerCodeReceiver, which always uses a random open port. I'm not sure how OAuthTokenGenerator works that way, since you need to know the port ahead of time to authorize the redirect url in the Google Console.

How do you use Google credentials of type "Other"?

I've added both 
http://localhost/authorize
http://127.0.0.1/authorize

Still no luck.
