### ISSUE TITLE
Is it normal that Google.Adwords.Examples.CSharp does not compile?

### ISSUE THREAD

**Issue by mayerwin** [googleads/googleads-dotnet-lib#58]
I have installed the latest version of Google.Adwords.Examples.CSharp from NuGet into a C# Console project, but there are a lot of compilation errors despite using Visual Studio 2015. Is this normal?
Also, why does this project contain old versions of code sample (e.g. 201502 folder)?

**Comment by AnashOommen** [comment]
Hi,

1. I pushed a release today that removes support for v201502.
2. No, it shouldn't. I'll take a look why nuget packages have issue compiling.

**Comment by mayerwin** [comment]
Thanks, why is the v201506 still included in the solution (and the API)? Is it for backward compatibility?

I still have a lot of errors due to "Adwords" not being properly qualified. For example in GetNewKeywords.cs, line 427:
`criterion = new AdWords.v201509.Keyword() {"` does not compile. To fix this I have to replace the line with a properly qualified name: `criterion = new Google.Api.Ads.AdWords.v201509.Keyword() {`.
Adding `using Google.Api.Ads;` does not work.

**Comment by AnashOommen** [comment]
Fixed in v18.20.0.
